services:
  init-opensearch-data:
    container_name: init-open-search
    image: busybox
    privileged: true
    command: >
      sh -c "sysctl -w vm.max_map_count=262144 && 
             chown -R 1000:1000 /usr/share/opensearch/data"
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data
    networks:
      - games

  opensearch:
    image: opensearchproject/opensearch:2.19.6
    container_name: opensearch
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Opensearch16admin#"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
      - plugins.ml_commons.controller_enabled=true
      - plugins.ml_commons.local_model.enabled=true
      - plugins.security.ssl.http.enabled=false
      - plugins.ml_commons.only_run_on_ml_node=false
      - plugins.ml_commons.model_access_control_enabled=false
      - plugins.ml_commons.native_memory_threshold=99
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data
    networks:
      - games
    
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - games

  sagebot:
    container_name: sagebot
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8501:8501
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=Opensearch16admin#
    networks:
      - games
    env_file:
      - .env
    volumes:
      - ./data:/app/data

networks:
  games:
    name: games

volumes:
  opensearch-data:
    driver: local
  postgres-data:
    name: postgres-data
